
/**
 |
 | The filler half of the programme: one line per session, no page content.
 |
 | `sessions.ts` writes eight sessions longhand — one for every branch a
 | session page can take — and then deals the rest of the programme out of this
 | table. Both become real Session entries; the difference is only that these
 | carry no content worth reading.
 |
 | They live here rather than beside the writer because the table is six
 | hundred lines long, and adding a session to the programme is a different job
 | from changing how a session is written.
 |
 | Every one of these becomes a page of its own, and what they are really for is
 | the category listings and the schedule page — **a listing capped at ten needs
 | more than ten sessions in one category before the cap is observable**, which
 | is why there are this many rather than a handful.
 |
 | They are thin by design: a name, a line, one instance and a venue. The
 | eight in `sessions.ts` carry the content worth reading; these carry the
 | count.
 |
 */
export const PROGRAMME = [
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined as string | undefined,
		day: "2025-12-11",
		from: "10:00",
		name: "Reweaving the Ecosystem",
		price: 1599,
		standfirst:
			"India’s fading indigenous cotton, and the people still growing it.",
		to: "20:00",
		venue: "Gallery One",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-12",
		from: "10:00",
		name: "Making the Invisible Visible",
		price: 1599,
		standfirst:
			"Indoor heat, unpaid domestic work and women’s resilience.",
		to: "20:00",
		venue: "Gallery One",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "10:00",
		name: "The Force Within",
		price: 0,
		standfirst: "A room that answers to the weather outside it.",
		to: "20:00",
		venue: "Gallery Two",
		year: 2025,
	},
	{
		age_group: "Children",
		category: "Experience",
		checkout_url: "https://example.com/cc/shade-garden",
		day: "2025-12-12",
		from: "09:30",
		name: "The Shade Garden",
		price: 0,
		standfirst: "Forty species that ask for no water and give back shade.",
		to: "18:00",
		venue: "North Lawn",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Experience",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "09:30",
		name: "Soundings from the Mangrove",
		price: 300,
		standfirst:
			"Two years of recordings from the creek, played back at scale.",
		to: "18:00",
		venue: "The Dark Room",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2025-12-11",
		from: "15:00",
		name: "Who Pays for Cool",
		price: undefined as number | undefined,
		standfirst: "Cooling as a right, and who is left out of it.",
		to: "16:30",
		venue: "The Conversation Stage",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "15:00",
		name: "Building with What Is Already There",
		price: undefined,
		standfirst: "Reuse, retrofit and the case against the new.",
		to: "16:30",
		venue: "The Conversation Stage",
		year: 2025,
	},
	{
		age_group: "Children",
		category: "Workshop",
		checkout_url: "https://example.com/cc/clay-pots",
		day: "2025-12-11",
		from: "11:00",
		name: "Cooling Pots in Clay",
		price: 350,
		standfirst: "Throw a pot that keeps water cold without a plug.",
		to: "13:00",
		venue: "Studio One",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Workshop",
		checkout_url: "https://example.com/cc/reading-a-site",
		day: "2025-12-13",
		from: "11:00",
		name: "Reading a Site for Heat",
		price: 900,
		standfirst:
			"An afternoon with a thermal camera and a plan of the plant.",
		to: "14:00",
		venue: "Studio Two",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Experience",
		checkout_url: undefined,
		day: "2027-12-02",
		from: "10:00",
		name: "A First Walk Through 2027",
		price: undefined,
		standfirst: "The site as it stands, a year out.",
		to: "17:00",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "All",
		category: "Workshop",
		checkout_url: undefined,
		day: "2027-12-04",
		from: "11:00",
		name: "Drawing What Comes Next",
		price: undefined,
		standfirst:
			"An open table for whoever wants a hand in what comes next.",
		to: "13:00",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-11",
		from: "10:00",
		name: "Terracotta, Recast",
		price: 1599,
		standfirst:
			"A roof tile redrawn for a city that no longer cools at night.",
		to: "20:00",
		venue: "Gallery One",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-12",
		from: "10:00",
		name: "The Weight of Water",
		price: 1200,
		standfirst: "What a household carries, measured over one summer week.",
		to: "20:00",
		venue: "Gallery Two",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "10:00",
		name: "Kiln and Contour",
		price: 0,
		standfirst: "Fired earth shaped to the land it came out of.",
		to: "20:00",
		venue: "Gallery Two",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-11",
		from: "10:00",
		name: "Threads of the Deccan",
		price: 1599,
		standfirst: "Six weaving households, one loom rebuilt in the round.",
		to: "20:00",
		venue: "Gallery One",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-11",
		from: "10:00",
		name: "A Wall That Breathes",
		price: undefined,
		standfirst: "A prototype facade tested through three Mumbai summers.",
		to: "20:00",
		venue: "North Lawn",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-12",
		from: "10:00",
		name: "Salt, Sun, Settlement",
		price: 1200,
		standfirst: "The Rann as a drawing, over sixty years.",
		to: "20:00",
		venue: "Gallery Three",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "10:00",
		name: "After the Monsoon",
		price: undefined,
		standfirst: "What the water leaves, and what is built on it.",
		to: "20:00",
		venue: "Gallery Three",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2025-12-12",
		from: "10:00",
		name: "Common Ground",
		price: 0,
		standfirst: "Twelve courtyards, photographed at the same hour.",
		to: "20:00",
		venue: "Gallery Three",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Experience",
		checkout_url: undefined,
		day: "2025-12-11",
		from: "09:30",
		name: "The Listening Room",
		price: 300,
		standfirst: "Sit for ten minutes with a city you cannot see.",
		to: "18:00",
		venue: "The Dark Room",
		year: 2025,
	},
	{
		age_group: "Children",
		category: "Experience",
		checkout_url: undefined,
		day: "2025-12-12",
		from: "09:30",
		name: "Barefoot on Seven Surfaces",
		price: 0,
		standfirst: "Stone, clay, grass, gravel, tile, timber and tar.",
		to: "18:00",
		venue: "North Lawn",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Experience",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "09:30",
		name: "A Room at Forty Degrees",
		price: undefined,
		standfirst: "Ten minutes inside the summer we are designing for.",
		to: "18:00",
		venue: "Pavilion",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Experience",
		checkout_url: "https://example.com/cc/long-table",
		day: "2025-12-11",
		from: "12:00",
		name: "The Long Table",
		price: 450,
		standfirst: "Eat with strangers, at a table built for the week.",
		to: "15:00",
		venue: "North Lawn",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Experience",
		checkout_url: undefined,
		day: "2025-12-11",
		from: "11:00",
		name: "Wind Tunnel, Slowly",
		price: undefined,
		standfirst: "Watch air find its way through six plans.",
		to: "17:00",
		venue: "Pavilion",
		year: 2025,
	},
	{
		age_group: "Children",
		category: "Experience",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "11:00",
		name: "Ink and Rain",
		price: 0,
		standfirst: "A drawing finished by the weather.",
		to: "17:00",
		venue: "Studio One",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2025-12-12",
		from: "15:00",
		name: "The Cost of Comfort",
		price: undefined,
		standfirst: "Who pays for the air conditioning, and who cannot.",
		to: "16:30",
		venue: "The Conversation Stage",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "11:00",
		name: "Drawing for the Unbuilt",
		price: undefined,
		standfirst: "Three practices on the work that never breaks ground.",
		to: "12:30",
		venue: "The Conversation Stage",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Conversation",
		checkout_url: undefined,
		day: "2025-12-11",
		from: "17:00",
		name: "What the Craftsperson Knows",
		price: undefined,
		standfirst: "Knowledge that never made it into a specification.",
		to: "18:30",
		venue: "The Conversation Stage",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2025-12-12",
		from: "11:00",
		name: "Material Honesty, Revisited",
		price: 0,
		standfirst: "An old argument, put to people who build now.",
		to: "12:30",
		venue: "Seminar Room",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2025-12-11",
		from: "11:00",
		name: "Heat and the Working Day",
		price: undefined,
		standfirst: "Labour, shade and the hours nobody schedules.",
		to: "12:30",
		venue: "Seminar Room",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Conversation",
		checkout_url: undefined,
		day: "2025-12-13",
		from: "17:00",
		name: "Twenty Years of the Lab",
		price: undefined,
		standfirst: "What the Lab set out to do, and what it did.",
		to: "18:30",
		venue: "The Conversation Stage",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Workshop",
		checkout_url: "https://example.com/cc/lime-plaster",
		day: "2025-12-12",
		from: "09:30",
		name: "Lime Plaster, Start to Finish",
		price: 1200,
		standfirst: "Slake, mix, float. One panel each, taken home wet.",
		to: "13:00",
		venue: "Studio One",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Workshop",
		checkout_url: "https://example.com/cc/bamboo-joints",
		day: "2025-12-13",
		from: "14:00",
		name: "Bamboo Joints Without Nails",
		price: 800,
		standfirst: "Six joints, a saw and an afternoon.",
		to: "17:00",
		venue: "Studio Two",
		year: 2025,
	},
	{
		age_group: "Children",
		category: "Workshop",
		checkout_url: "https://example.com/cc/natural-dye",
		day: "2025-12-12",
		from: "09:30",
		name: "Natural Dye from the Kitchen",
		price: 0,
		standfirst: "Onion skin, turmeric, tea and iron.",
		to: "12:00",
		venue: "Studio One",
		year: 2025,
	},
	{
		age_group: "Adults",
		category: "Workshop",
		checkout_url: "https://example.com/cc/the-section",
		day: "2025-12-11",
		from: "14:00",
		name: "Drawing the Section",
		price: 600,
		standfirst: "The one drawing that says how a building works.",
		to: "17:00",
		venue: "Seminar Room",
		year: 2025,
	},
	{
		age_group: "Children",
		category: "Workshop",
		checkout_url: undefined,
		day: "2025-12-12",
		from: "16:00",
		name: "Paper, Folded for Shade",
		price: 0,
		standfirst: "A screen you fold in two hours and unfold at home.",
		to: "18:00",
		venue: "Studio Two",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Workshop",
		checkout_url: "https://example.com/cc/your-street",
		day: "2025-12-12",
		from: "14:00",
		name: "Measuring Your Own Street",
		price: undefined,
		standfirst: "A tape, a thermometer and one hour outside.",
		to: "15:30",
		venue: "Plant 13 Gate",
		year: 2025,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2027-12-02",
		from: "10:00",
		name: "Site Notes: The North Yard",
		price: undefined,
		standfirst: "What is there now, before anything is proposed.",
		to: "18:00",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "All",
		category: "Showcase",
		checkout_url: undefined,
		day: "2027-12-03",
		from: "10:00",
		name: "Site Notes: The Water Tank",
		price: undefined,
		standfirst: "A structure nobody has decided what to do with.",
		to: "18:00",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2027-12-02",
		from: "15:00",
		name: "An Open Brief",
		price: undefined,
		standfirst: "The theme, still being argued about, in public.",
		to: "16:30",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2027-12-03",
		from: "15:00",
		name: "Who Should Be Here",
		price: undefined,
		standfirst: "On who the next one is actually for.",
		to: "16:30",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "Adults",
		category: "Conversation",
		checkout_url: undefined,
		day: "2027-12-05",
		from: "11:00",
		name: "Two Years of Lead Time",
		price: undefined,
		standfirst: "What can be built when there is time to build it.",
		to: "12:30",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "All",
		category: "Experience",
		checkout_url: undefined,
		day: "2027-12-03",
		from: "10:00",
		name: "Prototype Yard",
		price: undefined,
		standfirst: "Half-finished things, shown on purpose.",
		to: "17:00",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "All",
		category: "Experience",
		checkout_url: undefined,
		day: "2027-12-04",
		from: "10:00",
		name: "The Shade Trial",
		price: undefined,
		standfirst: "Six canopies, one summer, no conclusions yet.",
		to: "17:00",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "Adults",
		category: "Experience",
		checkout_url: undefined,
		day: "2027-12-05",
		from: "10:00",
		name: "A Walk with the Engineers",
		price: undefined,
		standfirst: "The plant as the people who run it see it.",
		to: "17:00",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "Adults",
		category: "Workshop",
		checkout_url: undefined,
		day: "2027-12-02",
		from: "11:00",
		name: "Making the Brief",
		price: undefined,
		standfirst: "Bring a proposal; leave with it argued over.",
		to: "13:00",
		venue: "Plant 13",
		year: 2027,
	},
	{
		age_group: "Adults",
		category: "Workshop",
		checkout_url: undefined,
		day: "2027-12-05",
		from: "14:00",
		name: "Casting a Test Panel",
		price: undefined,
		standfirst: "One panel, one mix, one week to cure.",
		to: "16:00",
		venue: "Plant 13",
		year: 2027,
	},
]
